apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: minicurso
spec:
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
  selector:
    app: nginx
  type: NodePort
status:
